name: publish-package

on:
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: publish-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # Fetches all commits (needed for lerna / semantic release to correctly calculate version)
          fetch-depth: 0
          # Whether to check out submodules: `true` to check out submodules or `recursive` to recursively check out submodules.
          submodules: "recursive"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: ./global.json

      - name: Install dependencies
        run: dotnet restore
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
